name: Deploy

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'deploy-staging' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      
    - name: Run a one-line script
      run: echo Hello, world!