name: Deploy

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'deploy-staging' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: SetUp Terraform
    - uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Init
      run: terraform init
      env: 
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

    - name: Terraform Format
      run: terraform fmt -check
      env: 
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      
    - name: Terraform Plan
      run: terraform plan 

    - name: Terraform Apply
      run: terraform apply 
      env:
        TF_ACTION_WORKING_DIR: 'terraform' 
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

    - name: Run a one-line script
      run: echo Hello, world!